dados = [
    {
        "nome": "Érico Borgonove",
        "genero": "Masculino",
        "cpf": "00000000000",
        "rg": "000000",
        "data_nascimento": "1987-09-16",
        "local_nascimento": "Aracaju",
        "estado_nascimento": "Sergipe",
        "can_drive": True,
        "can_vote": True,
        "matrimonial_state": "single",
        "degree": "Master"
    },
    {
        "nome": "Amanda da Luz",
        "genero": "Feminino",
        "cpf": "917.032.658-40",
        "rg": "514806722",
        "data_nascimento": "1962-01-07",
        "local_nascimento": "da Rosa",
        "estado_nascimento": "Goiás",
        "can_drive": False,
        "can_vote": True,
        "matrimonial_state": "single",
        "degree": "High School"
    },
    {
        "nome": "Julia Mendes",
        "genero": "Feminino",
        "cpf": "126.089.473-87",
        "rg": "634017858",
        "data_nascimento": "1962-02-15",
        "local_nascimento": "Carvalho",
        "estado_nascimento": "Amapá",
        "can_drive": False,
        "can_vote": True,
        "matrimonial_state": "divorced",
        "degree": "High School"
    },
    {
        "nome": "Enrico Melo",
        "genero": "Masculino",
        "cpf": "849.603.527-10",
        "rg": "306178540",
        "data_nascimento": "1979-04-28",
        "local_nascimento": "Oliveira",
        "estado_nascimento": "Tocantins",
        "can_drive": True,
        "can_vote": True,
        "matrimonial_state": "single",
        "degree": "Bachelor"
    },
    {
        "nome": "Bianca Porto",
        "genero": "Feminino",
        "cpf": "479.385.062-65",
        "rg": "720461388",
        "data_nascimento": "1977-06-20",
        "local_nascimento": "da Costa",
        "estado_nascimento": "Minas Gerais",
        "can_drive": False,
        "can_vote": True,
        "matrimonial_state": "divorced",
        "degree": "High School"
    },
    {
        "nome": "André Pereira",
        "genero": "Feminino",
        "cpf": "981.576.230-30",
        "rg": "821403576",
        "data_nascimento": "1986-12-22",
        "local_nascimento": "Carvalho",
        "estado_nascimento": "Espírito Santo",
        "can_drive": False,
        "can_vote": True,
        "matrimonial_state": "married",
        "degree": "Doctorate"
    },
    {
        "nome": "Sr. Cauê Monteiro",
        "genero": "Feminino",
        "cpf": "372.961.508-40",
        "rg": "748602537",
        "data_nascimento": "1958-08-11",
        "local_nascimento": "Ferreira de Barbosa",
        "estado_nascimento": "Rio Grande do Norte",
        "can_drive": False,
        "can_vote": True,
        "matrimonial_state": "widowed",
        "degree": "High School"
    },
    {
        "nome": "Benício da Mata",
        "genero": "Masculino",
        "cpf": "612.035.874-90",
        "rg": "647320186",
        "data_nascimento": "1973-10-29",
        "local_nascimento": "da Mata das Pedras",
        "estado_nascimento": "Pernambuco",
        "can_drive": True,
        "can_vote": True,
        "matrimonial_state": "divorced",
        "degree": "Master"
    },
    {
        "nome": "Luiz Henrique Barbosa",
        "genero": "Feminino",
        "cpf": "794.106.385-93",
        "rg": "408726519",
        "data_nascimento": "1963-10-15",
        "local_nascimento": "Carvalho do Galho",
        "estado_nascimento": "Pernambuco",
        "can_drive": False,
        "can_vote": True,
        "matrimonial_state": "single",
        "degree": "Master"
    },
    {
        "nome": "Davi Luiz Costela",
        "genero": "Feminino",
        "cpf": "469.253.871-64",
        "rg": "580632714",
        "data_nascimento": "1954-07-07",
        "local_nascimento": "Pereira do Sul",
        "estado_nascimento": "Santa Catarina",
        "can_drive": True,
        "can_vote": True,
        "matrimonial_state": "widowed",
        "degree": "Doctorate"
    },
    ...
]
